import pandas as pd
url = "https://raw.github.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/tips.csv"
datos = pd.read_csv(url)
print(datos)
print("Mostrando solo 4 columnas: 'total_bill','tip','smoker','time'")
datos2 = datos[['total_bill','tip','smoker','time']]
print(datos2)
print("Mostrando solo 2 columnas: 'total_bill' y 'day'")
datos3 = datos[['total_bill', 'day']]
print(datos3)
print("Mostrando las 7 columnas y solo los 5 primeros registros")
n_registros = 5
datos4 = datos.head(n_registros)
print(datos4)
print("Mostrando las 3 columnas: tip, sex y size con solo los 10 primeros registros")
datos4 = datos.head(10)
datos4 = datos4[['tip','sex','size']]
print(datos4)
print("Mostrando las 3 columnas: tip, sex y size con solo los 10 primeros registros")
datos5 = datos[['tip','sex', 'size']].head(10)
print(datos5)
print("Mostrando las 3 columnas: tip, sex y size con solo los 10 primeros registros")
n_registros = 10
datos5 = datos[["tip","sex","size"]]
datos5 = datos5.head(n_registros)
print(datos5)
booleanos = datos['time'] == 'Dinner'
print(booleanos)
print("Mostrando todos los registros donde time='Dinner'")
print(datos[booleanos])
booleanos = (datos["sex"]=="Female") & (datos['day']=='Sun')
print(datos[booleanos])
booleanos = (datos["sex"] == "Male") & (datos["day"] == "Fri") & (datos["smoker"] == "No")
print(datos[booleanos])
booleanos = ((datos["sex"] == "Male") & (datos["day"] == "Fri") & (datos["smoker"] == "Yes"))
print(datos[booleanos].head(8))
x = (datos['sex'] == "Male") & (datos["day"] == "Fri") & (datos["smoker"] == "Yes")
print(datos[x].head(8))
booleanos = datos['smoker']=='Yes'
conteos = booleanos.value_counts()
print(conteos)
print(conteos[1])
x = datos["smoker"] == "Yes"
print(len(datos[x]))
print("La cantidad de presonas fumadoras es {}".format(booleanos.value_counts()[1]))
print("Mostrar al cantidad de registros donde las personas son fumadores y el dia es domingo")
booleanos = ((datos["day"] == "Sun") & (datos["smoker"] == "Yes") )
conteos = booleanos.value_counts()
print("La cantidad de personas fumadoras en días domingos: ", conteos[1])
x = (datos["smoker"] == "Yes") & (datos["day"] == "Sun")
conteo = x.value_counts()
print("La cantidad de personas fumadoras en días domingos: ", conteo[1])
booleanos = ((datos["tip"] > 5) & (datos["time"] == "Dinner"))
print(datos[booleanos].head(10))
x = (datos["time"] == "Dinner") & (datos["tip"] > 5)
print(datos[x].head(10))
booleanos = ((datos["size"] > 5) & (datos["total_bill"] > 45))
conteos = booleanos.value_counts()
print(conteos[1])
x = (datos["total_bill"] > 45) & (datos["size"] > 5)
print(x.value_counts()[1])
x = (datos["size"] > 5) & (datos["total_bill"] > 45)
conteos = x.value_counts()
print("Cantidad:",conteos[1])
print(datos.groupby("sex").size())
print(datos.groupby("sex"))
print(datos.groupby("sex").size()[0])
print(datos.groupby("sex").size()[1])
print(datos.groupby('day').size())
print(datos.groupby('day').count())
print(datos.assign(tip_rate=datos['tip']/datos['total_bill']))
import numpy as np
print(datos.groupby('day').agg({'tip':np.mean, 'day':np.size}))
print(np.mean([16,18,20]))
print(np.size([1,2,4,54]))
datos7 = datos[datos['day']=='Fri']
print(np.mean(datos7['tip']))
print(np.size(datos7['day']))
print(datos.groupby('sex').agg({'tip':np.mean,'total_bill':np.mean}))
print(datos.groupby(['smoker','day']).agg({'tip':[np.size, np.mean]}))
